# Generated by Django 5.2.3 on 2025-06-27 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('futbol', 'Fútbol'), ('basket', 'Baloncesto'), ('tenis', 'Tenis')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInico', models.DateField()),
                ('fechaFin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], max_length=20)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cancha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodoPago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=20)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.reserva')),
            ],
        ),
    ]
