# Generated by Django 5.2.3 on 2025-07-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cancha_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancha',
            name='precioHora',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
