# Generated by Django 5.2.3 on 2025-07-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_cancha_detalles_cancha_preciohora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fechaInico',
            field=models.DateTimeField(),
        ),
    ]
