# Generated by Django 5.2.3 on 2025-07-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_reserva_fechainico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fechaFin',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fechaInico',
            new_name='fecha_inicio',
        ),
    ]
