# Generated by Django 5.2.3 on 2025-07-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_rename_fechafin_reserva_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='disponible',
        ),
    ]
