# Generated by Django 5.2.3 on 2025-07-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_remove_cancha_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodoPago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('pendiente', 'Pendiente')], max_length=20),
        ),
    ]
